# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studyhall',
            table='Studyhall',
        ),
    ]
