# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_enquries_expense'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enquries',
            table='Enquries',
        ),
        migrations.AlterModelTable(
            name='expense',
            table='Expenses',
        ),
    ]
